# Generated by Django 5.1.4 on 2024-12-13 04:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('homify', '0002_houses_price'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='onsale',
            table='onsale',
        ),
    ]
